spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    password: zq199613
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
